### ISSUE TITLE
Wrong color when hover brand name

### ISSUE THREAD

**Issue by jonesy-b-dev** [jonesy-b-dev/Portfolio#2]
When hovering over brand name (Jonas de Bruin) located at the top the text will get a wrong color
![2022-09-28_10h57_48](https://user-images.githubusercontent.com/59418915/192736313-f4d0eb7e-45bb-4e77-8d91-70c5e756b6b4.png)

**Comment by abitsalihu** [comment]
Hey @jonesy-b-dev, I would like to work on this issue. :)

**Comment by jonesy-b-dev** [comment]
Yo, @abitsalihu that sounds amazing! You can open up a branch for it and start working on it. :):)
